/**
 * Pure helpers for assembling a subagent run's report and its run-scoped
 * permissions (v2 target-mode envelope support, §11.3 / §13.2).
 *
 * Extracted from subagentRunner so the status-machine label and the envelope
 * write-scope merge can be unit-tested without booting the LLM pipeline.
 */

/** Inputs to the report status machine (mirrors runSubAgent's own state). */
export interface StatusInputs {
  aborted: boolean
  finalText: string
  lastError: string
  hitTokenBudget: boolean
  iterationsLeft: number
}

/**
 * Runner-side status label for the report first line (v2 §11.3): generated by
 * the runner's own state machine, never parsed from LLM text.
 *
 * Mirrors the original report fallback — a run is only "incomplete/failed"
 * when no final text was produced (tool errors the agent recovered from still
 * count as done):
 * - aborted (user stopped) → 阻塞
 * - hard error (no final text) → 失败
 * - token budget hit / iterations exhausted (no final text) → 部分完成
 * - otherwise → 完成
 */
export function subagentStatusLabel(st: StatusInputs): '完成' | '部分完成' | '阻塞' | '失败' {
  const hardError = !st.finalText && !!st.lastError
  const incomplete = (st.hitTokenBudget || (st.iterationsLeft <= 0 && !st.lastError)) && !st.finalText
  return st.aborted ? '阻塞' : hardError ? '失败' : incomplete ? '部分完成' : '完成'
}

/**
 * Merge the task envelope's `files_to_modify` into a definition's write scope
 * (v2 §11.2 / §13.2): the envelope becomes the run's write boundary on top of
 * the definition's own allowedWritePaths. Absent envelope paths → the
 * definition's scope is returned unchanged (plain runs keep their boundary).
 */
export function mergeWriteScopes(
  defWrite: string[] | undefined,
  envelopeWrite: string[] | undefined,
): string[] | undefined {
  if (!envelopeWrite || envelopeWrite.length === 0) return defWrite
  return [...(defWrite || []), ...envelopeWrite]
}

/**
 * Subagent model resolution (v2 §10.5 / §13.4): the envelope's per-role model
 * override wins, then the session model, then the config group default. Plain
 * runs pass no override → identical to the pre-v2 resolution.
 */
export function resolveSubagentModel(
  override: string | undefined,
  sessionModel: string | undefined,
  defaultModel: string | undefined,
): string {
  return override || sessionModel || defaultModel || ''
}
